module.exports = {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/introduction",
        "getting-started/account-recovery",
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "AirGap Vault",
      items: [
        "airgap-vault/introduction",
        {
          type: "category",
          label: "Security",
          items: [
            "airgap-vault/security/introduction",
            "airgap-vault/security/considerations",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Setup Cold Wallet",
          items: [
            "airgap-vault/setup/introduction",
            "airgap-vault/setup/ios",
            "airgap-vault/setup/android",
            "airgap-vault/setup/desktop",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Devices",
          items: [
            "airgap-vault/supported-devices",
            "airgap-vault/recommended-devices",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Features",
          items: [
            "airgap-vault/features/address-explorer",
            "airgap-vault/features/bip-39-wordlist",
            "airgap-vault/features/bip-85",
            "airgap-vault/features/dice-coin-entropy",
            "airgap-vault/features/key-generation",
            "airgap-vault/features/bip-39-passphrase",
            "airgap-vault/features/multi-wallet",
            "airgap-vault/features/multi-seed",
            "airgap-vault/features/secure-keyboard",
            "airgap-vault/features/social-recovery",
            "airgap-vault/features/sapling",
            "airgap-vault/features/address-book",
            "airgap-vault/features/multi-sig",
          ],
          collapsed: true,
        },
        "airgap-vault/features/comparison",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "AirGap Wallet",
      items: [
        "airgap-wallet/introduction",
        {
          type: "category",
          label: "Features",
          items: [
            "airgap-wallet/features/identicons",
            "airgap-wallet/features/darkmode",
            "airgap-wallet/features/api-check",
            "airgap-wallet/features/staking",
            "airgap-wallet/features/nfts",
          ],
          collapsed: true,
        },
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "AirGap Knox",
      items: [
        "airgap-knox/introduction",
        "airgap-knox/device",
        {
          type: "category",
          label: "Features",
          items: [
            "airgap-vault/features/address-explorer",
            "airgap-vault/features/bip-39-wordlist",
            "airgap-vault/features/bip-85",
            "airgap-vault/features/dice-coin-entropy",
            "airgap-vault/features/key-generation",
            "airgap-vault/features/bip-39-passphrase",
            "airgap-vault/features/multi-wallet",
            "airgap-vault/features/multi-seed",
            "airgap-vault/features/secure-keyboard",
            "airgap-vault/features/social-recovery",
            "airgap-vault/features/sapling",
            "airgap-vault/features/address-book",
            "airgap-vault/features/multi-sig",
          ],
          collapsed: true,
        },
        "airgap-knox/faqs",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Currencies",
      items: [
        {
          type: "category",
          label: "Bitcoin (BTC)",
          items: [
            "currencies/bitcoin/introduction",
            "currencies/bitcoin/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Ethereum (ETH)",
          items: [
            "currencies/ethereum/introduction",
            "currencies/ethereum/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Optimism ETH (ETH)",
          items: [
            "currencies/optimism/introduction",
            "currencies/optimism/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Tezos (XTZ)",
          items: [
            "currencies/tezos/introduction",
            "currencies/tezos/delegation",
            "currencies/tezos/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Polkadot (DOT)",
          items: [
            "currencies/polkadot/introduction",
            "currencies/polkadot/delegation",
            "currencies/polkadot/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Kusama (KSM)",
          items: [
            "currencies/kusama/introduction",
            "currencies/kusama/delegation",
            "currencies/kusama/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Moonbeam (GLMR)",
          items: [
            "currencies/moonbeam/introduction",
            "currencies/moonbeam/delegation",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Moonriver (MOVR)",
          items: [
            "currencies/moonriver/introduction",
            "currencies/moonriver/delegation",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Cosmos (ATOM)",
          items: [
            "currencies/cosmos/introduction",
            "currencies/cosmos/delegation",
            "currencies/cosmos/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Groestlcoin (GRS)",
          items: [
            "currencies/groestlcoin/introduction",
            "currencies/groestlcoin/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Aeternity (AE)",
          items: [
            "currencies/aeternity/introduction",
            "currencies/aeternity/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Internet Computer (ICP)",
          items: [
            "currencies/icp/introduction",
            "currencies/icp/delegation",
            "currencies/icp/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Coreum (CORE)",
          items: [
            "currencies/coreum/introduction",
            "currencies/coreum/delegation",
            "currencies/coreum/wallet-compatibility",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Rootstock (RBTC)",
          items: [
            "currencies/rootstock/introduction",
            "currencies/rootstock/wallet-compatibility",
          ],
          collapsed: true,
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Troubleshooting",
      items: [
        {
          type: "category",
          label: "General",
          items: ["troubleshooting/general/not-enough-balance"],
          collapsed: true,
        },
        {
          type: "category",
          label: "Bitcoin (BTC)",
          items: ["troubleshooting/currencies/bitcoin/transaction-stuck"],
          collapsed: true,
        },
        {
          type: "category",
          label: "Ethereum (ETH)",
          items: ["troubleshooting/currencies/ethereum/transaction-stuck"],
          collapsed: true,
        },
        {
          type: "category",
          label: "Tezos (XTZ)",
          items: ["troubleshooting/currencies/tezos/FAQ"],
          collapsed: true,
        },
        {
          type: "category",
          label: "Cosmos (ATOM)",
          items: ["troubleshooting/currencies/cosmos/FAQ"],
          collapsed: true,
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        "guides/metamask",
        "guides/metamask-mobile",
        "guides/specter",
        "guides/imToken",
        "guides/rabby",
        "guides/bip-85",
        "guides/sapling",
        "guides/social-recovery",
        "guides/step-by-step-guide",
        "guides/update-webview",
        "guides/vault-offline-update",
        "guides/blue-wallet",
        "guides/sparrow-wallet",
        "guides/interaction",
        "guides/temple",
        "guides/ledger",
        "guides/trezor",
        "guides/import-recovery-phrase",
        "guides/plate",
        "guides/bip-39-passphrase",
        "guides/dice-coin-entropy",
        "guides/address-book",
        "guides/blockwallet",
        "guides/safewallet",
        "guides/delegate-xtz",
        "guides/stake-xtz",
      ],
    },
    "isolated-module",
    "FAQ",
    "glossary",
    "CHANGELOG-VAULT",
    "CHANGELOG-WALLET",
    "UPCOMING",
    {
      type: "link",
      label: "AirGap Website",
      href: "https://airgap.it",
    },
  ],
  coinlib: [
    "coinlib/installation",
    {
      type: "category",
      label: "Examples",
      items: [
        "coinlib/examples/get-address",
        "coinlib/examples/get-btc-addresses-from-account-share",
        "coinlib/examples/serializer/v2/introduction",
      ],
      collapsed: true,
    },
  ],
};
